### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by photodude**
- Use Arturo Command line toolkit rather than a stale fork of INO
- update to arduino-1.6.1 ide

### CODE REVIEW

**Comment by kyab** [comment]
Thanks I didn't know Arturo.

**Comment by photodude** [comment]
@kyab I didn't either, I had commented on a PR in the amperka/ino project and @scottdarch who manages Arturo passed on the information. 

I will mention that it probably was a little early to submit and merge this PR as the build is failing due to a build error. I think I didn't get the Arduino 1.6.1 IDE git clone set up correctly. I'll try looking at this again tonight and submit a PR to fix the issue.

**Comment by kyab** [comment]
@photodude Yes it was littler early to merge your PR but I think it was OK to go ahead to debug Travis :-).
Now succeeded to launch avr-gcc but failed.
https://travis-ci.org/kyab/travis-test-arduino/builds/63520781

It seems like some problem on Arturo's mcu select process.
Anyway I'll merge your another PR cause it seems required.

**Comment by photodude** [comment]
@kyab Based on what I've looked at there likely is a command line argument that needs to be included  with Arturo's ano line for running the scripts to specify an MCU for the build.

**Comment by kyab** [comment]
@photodude I've changed target board to Uno and waiting Travis start. Thanks!

**Comment by photodude** [comment]
@kyab Thank you, Hopefully with your example and Arturo I will be able to have all my arduino projects tested on Travis CI. 
Then I'll have to see about adding Unit testing https://github.com/mmurdoch/arduinounit

**Comment by scottdarch** [comment]
Awesome to see Arturo1 in use on travis! With Arturo2 I'm concentrating on making it work with Travis and other CI build systems so let me know what pain points 1.0 has.

**Comment by photodude** [comment]
@scottdarch I would say the first pain point is dependencies. I think ideally when installing Arturo with travis it should get the Arduino IDE as a git submodule and other PIP dependencies without the need to specify those dependencies in the `.travis.yml` file.

I'm thinking I'll try doing a multi-board environment testing set up next which will make use of specifying the board

**Comment by photodude** [comment]
@kyab Great to see the build succeeding.

**Comment by kyab** [comment]
@scottdarch Thanks you for developing Arturo!. I currently didn't have pain. 
Actually annoying part for me was that Arduino IDE did not have 64bit compiler but Travis runs Ubuntu 64bit. But it was issue on Arduino IDE itself, and now Arduino IDE has 64bit compiler so there are no problem.

@photodude "default board selection is falling on Travis" was not fault in Arturo. I used board type "arduino_due_x_dbg", that was incorrect name(at least for newer Arduino IDE).

**Comment by photodude** [comment]
@kyab looks like the `arduino_due_x_dbg causing unrecognized command line option '-mmcu=cortex-m3'` is an Arturo and ino issue, that board is listed when you run the list-models option.
I found another person who ran into that issue with ino, unfortunately no resolution in their post.  
http://blogs.sequoiainc.com/blogs/udoo-board-command-line-arduino-an-open-challenge

**Comment by scottdarch** [comment]
@photodude how can I reproduce the arduino_due_x_dbg failure? I don't have the board listed in my current environment.

**Comment by photodude** [comment]
@scottdarch what is your current environment? We have 1.6.1 IDE and the current master branch of Arturo. You can look at the [list I got from `ano list-models`](https://travis-ci.org/photodude/travis-test-arduino/builds/63667379)

**Comment by scottdarch** [comment]
@photodude I have 1.6.1 but it doesn't come out-of-the-box with the last two boards you have listed. Did those come from some other source like a library or something?

**Comment by photodude** [comment]
@scottdarch there is an install from source via `wget http://downloads-02.arduino.cc/arduino-1.6.1-linux64.tar.xz` in the [.travis.yml file](https://github.com/kyab/travis-test-arduino/blob/master/.travis.yml). No special libraries or other sources included outside of Arturo.

**Pull request merged**
